services:
  jupyter:
    build: .
    volumes:
      - .:/workspace
    environment:
      - PYTHONPATH=/src
    ports:
      - "8888:8888"
    command: jupyter lab --ip 0.0.0.0 --port 8888 --allow-root --no-browser --NotebookApp.token='lossaversion'
